### ISSUE TITLE
error trying to run python transcript_api_server.py in pipenv shell

### ISSUE THREAD

**Issue by Alysha-94** [persephone-tools/persephone-web-API#173]
following the steps in https://persephone-web-api.readthedocs.io/en/latest/development.html
there is an error when I run python transcript_api_server.py

here is the stacktrace, all the dependencies have downloaded successfully and after running 
cd /vagrant
pipenv install
pipenv shell
I tried python transcript_api_server.py and python3 transcript_api_server.py with the following errors

```
Last login: Thu Mar  7 00:54:04 2019 from 10.0.2.2
vagrant@vagrant:~$ cd /vagrant
vagrant@vagrant:/vagrant$ pipenv install
Installing dependencies from Pipfile.lock (3c47dc)…
  :snake:   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 60/60 — 00:01:07
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
vagrant@vagrant:/vagrant$ pipenv shell
Launching subshell in virtual environment…
vagrant@vagrant:/vagrant$  . /home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/bin/activate
(vagrant) vagrant@vagrant:/vagrant$ python transcription_api_server.py
Failed to add operation for POST /v0.1/model/train/{modelID}
Unhandled exception
Traceback (most recent call last):
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 262, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 215, in add_operation
    pass_context_arg_name=self.pass_context_arg_name)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/operation.py", line 228, in __init__
    resolution = resolver.resolve(self)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/resolver.py", line 67, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: module 'tensorflow.python.platform.self_check' has no attribute 'preload_check'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transcription_api_server.py", line 9, in <module>
    app = create_app(DevConfig)
  File "/vagrant/persephone_api/app.py", line 21, in create_app
    register_swagger_api(connexion_app)
  File "/vagrant/persephone_api/app.py", line 40, in register_swagger_api
    validate_responses=True
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apps/abstract.py", line 162, in add_api
    options=api_options.as_dict())
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 146, in __init__
    self.add_paths()
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 269, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 283, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/utils.py", line 36, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/vagrant/persephone_api/api_endpoints/model.py", line 12, in <module>
    from persephone import experiment
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/src/persephone/persephone/experiment.py", line 12, in <module>
    from . import rnn_ctc
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/src/persephone/persephone/rnn_ctc.py", line 8, in <module>
    import tensorflow as tf
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
AttributeError: module 'tensorflow.python.platform.self_check' has no attribute 'preload_check'
(vagrant) vagrant@vagrant:/vagrant$ python3 transcription_API_server.py

Failed to add operation for POST /v0.1/model/transcribe/{modelID}/{audioID}
Unhandled exception
Traceback (most recent call last):
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 262, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 215, in add_operation
    pass_context_arg_name=self.pass_context_arg_name)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/operation.py", line 228, in __init__
    resolution = resolver.resolve(self)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/resolver.py", line 67, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: module 'tensorflow.python.platform.self_check' has no attribute 'preload_check'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transcription_API_server.py", line 9, in <module>
    app = create_app(DevConfig)
  File "/vagrant/persephone_api/app.py", line 21, in create_app
    register_swagger_api(connexion_app)
  File "/vagrant/persephone_api/app.py", line 40, in register_swagger_api
    validate_responses=True
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apps/abstract.py", line 162, in add_api
    options=api_options.as_dict())
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 146, in __init__
    self.add_paths()
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 269, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/apis/abstract.py", line 283, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/connexion/utils.py", line 36, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/vagrant/persephone_api/api_endpoints/model.py", line 12, in <module>
    from persephone import experiment
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/src/persephone/persephone/experiment.py", line 12, in <module>
    from . import rnn_ctc
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/src/persephone/persephone/rnn_ctc.py", line 8, in <module>
    import tensorflow as tf
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
AttributeError: module 'tensorflow.python.platform.self_check' has no attribute 'preload_check'
```

**Comment by shuttle1987** [comment]
This looks like an install issue to me, for some reason it looks like tensorflow didn't install properly.

**Comment by Alysha-94** [comment]
I have realised this has possibly been due to a storage space issue

The first time I ran pipenv install I had to free up some space on my computer to download the dependencies, so I cleared some space and ran the commands again.

```
C:\Users\HP\Documents\CPS\persephone\persephone-web-API>vagrant ssh
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

68 packages can be updated.
51 updates are security updates.


vagrant@vagrant:~$ cd /vagrant
vagrant@vagrant:/vagrant$ pipenv install
Creating a virtualenv for this project…
Pipfile: /vagrant/Pipfile
Using /usr/bin/python3.5m (3.5.2) to create virtualenv…
⠴ Creating virtual environment...Using base prefix '/usr'
New python executable in /home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/bin/python3.5m
Also creating executable in /home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python3.5m
✔ Successfully created virtual environment!
Virtualenv location: /home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3
Installing dependencies from Pipfile.lock (3c47dc)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/60 — 00:00:00
C:\Users\HP\Documents\CPS\persephone\persephone-web-API>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.2.22
    default: VirtualBox Version: 6.0
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/HP/Documents/CPS/persephone/persephone-web-API
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

C:\Users\HP\Documents\CPS\persephone\persephone-web-API>vagrant ssh
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

68 packages can be updated.
51 updates are security updates.


Last login: Thu Mar  7 00:54:04 2019 from 10.0.2.2
vagrant@vagrant:~$ cd /vagrant
vagrant@vagrant:/vagrant$ pipenv install
Installing dependencies from Pipfile.lock (3c47dc)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 60/60 — 00:01:07
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
vagrant@vagrant:/vagrant$ pipenv shell
Launching subshell in virtual environment…
vagrant@vagrant:/vagrant$  . /home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/bin/activate
(vagrant) vagrant@vagrant:/vagrant$ python transcription_api_server.py
Failed to add operation for POST /v0.1/model/train/{modelID}
```

I tried to restart all the commands from the start just in case there was an issue with cancelling and restarting the dependency downloads and now I have it working

**Comment by shuttle1987** [comment]
Thanks for opening this issue, it seems like this was just the result of the install failing the first time for a reason unrelated to the project here so I'm going to close this.
